#!/bin/sh
# Simple udhcpc script for LJOS

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

RESOLV_CONF="/etc/resolv.conf"

case "$1" in
    deconfig)
        ifconfig $interface 0.0.0.0
        ;;
    renew|bound)
        ifconfig $interface $ip netmask ${subnet:-255.255.255.0}
        if [ -n "$router" ] ; then
            for i in $router ; do
                route add default gw $i dev $interface 2>/dev/null
            done
        fi
        if [ -n "$dns" ] ; then
            echo -n > $RESOLV_CONF
            for i in $dns ; do
                echo "nameserver $i" >> $RESOLV_CONF
            done
        fi
        ;;
esac
exit 0
